//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Id { get; set; }
        public int TimeTableId { get; set; }
        public int StudentId { get; set; }
        public bool IsExisted { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
