//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Teacher
    {
        public int Id { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
