//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section_Student()
        {
            this.StudentExisted = new HashSet<StudentExisted>();
        }
    
        public int Id { get; set; }
        public int SectionId { get; set; }
        public int StudentId { get; set; }
        public bool IsRegistered { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExisted> StudentExisted { get; set; }
    }
}
