//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExisted
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<bool> IsExisted { get; set; }
        public Nullable<int> idLesson { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
