//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public int TimeId { get; set; }
        public int SectionId { get; set; }
        public int TeacherId { get; set; }
        public int CabinetId { get; set; }
        public Nullable<int> DayId { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Day Day { get; set; }
        public virtual Section Section { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Time Time { get; set; }
    }
}
